esphome:
  name: esphome-aw9523

external_components:
  - source:
      type: local
      path: components

esp32:
  board: featheresp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

i2c:
  scan: false

aw9523:
  - id: aw9523_1
    address: 0x58
    divider: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

light:
  - platform: monochromatic
    name: "AW9523 #00"
    output: aw9523_pin_0
  - platform: monochromatic
    name: "AW9523 #01"
    output: aw9523_pin_1
  - platform: monochromatic
    name: "AW9523 #02"
    output: aw9523_pin_2
  - platform: monochromatic
    name: "AW9523 #15"
    output: aw9523_pin_15

output:
  - platform: aw9523
    aw9523: aw9523_1
    id: aw9523_pin_0
    max_current: 10 mA
    pin: 0
  - platform: aw9523
    aw9523: aw9523_1
    id: aw9523_pin_1
    max_current: 9.25 mA
    pin: 1
  - platform: aw9523
    aw9523: aw9523_1
    id: aw9523_pin_2
#    max_current: 10 mA
    pin: 2
  - platform: aw9523
    aw9523: aw9523_1
    id: aw9523_pin_15
    max_current: 10
    pin: 15
binary_sensor:
  - platform: gpio
    name: "AW9523 Pin #14"
    pin:
      aw9523: aw9523_1
      number: 14
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "AW9523 Pin #03"
    pin:
      aw9523: aw9523_1
      number: 3
      mode:
        input: true
      inverted: true
# Individual binary outputs
switch:
  - platform: gpio
    name: "AW9523 Pin #12"
    pin:
      aw9523: aw9523_1
      number: 12
      mode:
        output: true
  - platform: gpio
    name: "AW9523 Pin #04"
    pin:
      aw9523: aw9523_1
      number: 4
      mode:
        output: true